export const paymentTypes: { [key: string]: any } = {
  mobileAuto: {
    method: 'mobile',
    autoPayType: 'M',
    corpPayCode: '',
  },
  payco: {
    method: 'corp',
    autoPayType: '',
    corpPayCode: 'PAC',
  },
  kakao: {
    method: 'corp',
    autoPayType: '',
    corpPayCode: 'KKP',
  },
  nvpay: {
    method: 'corp',
    autoPayType: '',
    corpPayCode: 'NVP',
  },
};

export interface PaymentParamsModel {
  method: string;
  trdDt: string;
  trdTm: string;
  mchtName: string;
  mchtEName: string;
  pmtPrdtNm: string;
  notiUrl: string;
  nextUrl: string;
  cancUrl: string;
  plainMchtCustNm: string;
  custAcntSumry: string;
  expireDt: string;
  mchtParam: string;
  plainCphoneNo: string;
  plainEmail: string;
  telecomCd: string;
  prdtTerm: string;
  plainMchtCustId: number;
  taxTypeCd: string;
  plainTaxAmt: string;
  plainVatAmt: string;
  plainTaxFreeAmt: string;
  plainSvcAmt: string;
  cardType: string;
  chainUserId: string;
  cardGb: string;
  plainClipCustNm: string;
  plainClipCustCi: string;
  plainClipCustPhoneNo: string;
  certNotiUrl: string;
  skipCd: string;
  multiPay: string;
  autoPayType: string;
  linkMethod: string;
  appScheme: string;
  custIp: string;
  corpPayCode: string;
  corpPayType: string;
  cashRcptUIYn: string;
  respMchtId: string;
  respOutStatCd: string;
  respOutRsltCd: string;
  respOutRsltMsg: string;
  respMethod: string;
  respMchtTrdNo: string;
  respMchtCustId: string;
  respTrdNo: string;
  respTrdAmt: string;
  respMchtParam: string;
  respAuthDt: string;
  respAuthNo: string;
  respReqIssueDt: string;
  respIntMon: string;
  respFnNm: string;
  respFnCd: string;
  respPointTrdNo: string;
  respPointTrdAmt: string;
  respCardTrdAmt: string;
  respVtlAcntNo: string;
  respExpireDt: string;
  respCphoneNo: string;
  respBillKey: string;
  respCsrcAmt: string;
  trdAmt: string;
  mchtCustNm: string;
  cphoneNo: string;
  email: string;
  mchtCustId: string;
  taxAmt: string;
  vatAmt: string;
  taxFreeAmt: string;
  svcAmt: string;
  clipCustNm: string;
  clipCustCi: string;
  clipCustPhoneNo: string;
  mchtTrdNo: string;
  modelId: number;
  mchtId: string;
  plainTrdAmt: string;
}

export const params: PaymentParamsModel = {
  method: '',
  trdDt: '',
  trdTm: '',
  mchtName: '리딩수학',
  mchtEName: 'Reading Math',
  pmtPrdtNm: '',
  notiUrl: '',
  nextUrl: '',
  cancUrl: '',
  plainMchtCustNm: '',
  custAcntSumry: '',
  expireDt: '',
  mchtParam: '',
  plainCphoneNo: '',
  plainEmail: '',
  telecomCd: '',
  prdtTerm: '20221231235959',
  plainMchtCustId: 0,
  taxTypeCd: '',
  plainTaxAmt: '',
  plainVatAmt: '',
  plainTaxFreeAmt: '',
  plainSvcAmt: '',
  cardType: '',
  chainUserId: '',
  cardGb: '',
  plainClipCustNm: '',
  plainClipCustCi: '',
  plainClipCustPhoneNo: '',
  certNotiUrl: '',
  skipCd: '',
  multiPay: '',
  autoPayType: '',
  linkMethod: '',
  appScheme: '',
  custIp: '',
  corpPayCode: '',
  corpPayType: '',
  cashRcptUIYn: '',
  respMchtId: '',
  respOutStatCd: '',
  respOutRsltCd: '',
  respOutRsltMsg: '',
  respMethod: '',
  respMchtTrdNo: '',
  respMchtCustId: '',
  respTrdNo: '',
  respTrdAmt: '',
  respMchtParam: '',
  respAuthDt: '',
  respAuthNo: '',
  respReqIssueDt: '',
  respIntMon: '',
  respFnNm: '',
  respFnCd: '',
  respPointTrdNo: '',
  respPointTrdAmt: '',
  respCardTrdAmt: '',
  respVtlAcntNo: '',
  respExpireDt: '',
  respCphoneNo: '',
  respBillKey: '',
  respCsrcAmt: '',
  trdAmt: '',
  mchtCustNm: '',
  cphoneNo: '',
  email: '',
  mchtCustId: '',
  taxAmt: '',
  vatAmt: '',
  taxFreeAmt: '',
  svcAmt: '',
  clipCustNm: '',
  clipCustCi: '',
  clipCustPhoneNo: '',
  mchtTrdNo: '',
  modelId: 0,
  mchtId: '',
  plainTrdAmt: '',
};
